Remove fft992 and Bluestein FFT functionality
ecmwf-ifs/ectrans pull request #104
Opened 2024-06-04 10:00 UTC by samhatfield

This makes FFTW a required package.c

@marsdeno @ioanhadade - this is what it looks like without fft992 and Bluestein. It's a more invasive change than I expected!

2024-06-04 10:38 UTC, samhatfield commented
Note: API change on `SETUP_TRANS`, with removal of `LDUSEFFTW` argument.

2024-06-26 13:49 UTC, samhatfield commented
Given the recent interest in developments like https://github.com/ecmwf-ifs/ectrans/pull/100 I think we should take the plunge and merge this PR. 

Any objections @wdeconinck @marsdeno ?

2024-06-26 16:02 UTC, marsdeno commented
No objections from me, I agree we should go for it as this unblocks subsequent changes.

2024-06-27 08:20 UTC, samhatfield commented
I forgot to appoint official reviewers!

2024-06-27 08:21 UTC, wdeconinck commented
OK, I agree as well then. We could always make an adaptor library of bluestein / fft992 (if needed) in the future that follows the FFTW API, at which point.
Definitely we need a CPU ifs-bundle test with this though before merging into main.
I would request we keep the outward facing API unchanged (optional argument LDUSEFFTW) but print a deprecation message (non-severe warning) if it is provided, so that downstream packages are aware to remove this argument in the call-site at their own pace.

2024-06-27 08:25 UTC, wdeconinck requested changes

2024-06-27 08:25 UTC, wdeconinck commented on src/trans/external/setup_trans.F90
> -&LDSPSETUPONLY,LDPNMONLY,LDUSEFFTW,&
As mentioned in PR comments, please leave LDUSEFFTW for the moment but print deprecation message when `present(LDUSEFFTW)`.

2024-06-27 08:25 UTC, wdeconinck commented on src/trans/include/ectrans/setup_trans.h
> -&LDSPSETUPONLY,LDPNMONLY,LDUSEFFTW,&
And here to match interface.

2024-06-27 15:48 UTC, DJDavies2 commented
Just a question, I tried building this and got this cmake failure:

CMake Error at /home/h01/david.davies/cylc-run/ectrans-104-build-stack/share/mobbs/util/exz_gnu/share/ecbuild/cmake/ecbuild_log.cmake:190 (message):
  [1;35mCRITICAL - ectrans FAILED to find REQUIRED package FFTW

  find_package(FFTW) used a FindFFTW module to find FFTW

    Please check file `/home/h01/david.davies/cylc-run/ectrans-104-build-stack/share/mobbs/util/exz_gnu/share/ecbuild/cmake/FindFFTW.cmake` for help on setting variables to find this package.[m
Call Stack (most recent call first):
  /home/h01/david.davies/cylc-run/ectrans-104-build-stack/share/mobbs/util/exz_gnu/share/ecbuild/cmake/ecbuild_find_package.cmake:342 (ecbuild_critical)
  ectrans/CMakeLists.txt:58 (ecbuild_find_package)

It looks like there is a change of dependencies regarding fftw?  Is this correct?

2024-06-27 16:08 UTC, samhatfield commented
That is correct. FFTW would become a mandatory feature if this is merged. Does this error mean that up until now you have not been using FFTW with ecTrans? If so that's valuable feedback! We were under the assumption that everybody uses FFTW.

2024-06-27 16:25 UTC, DJDavies2 commented
I hadn't really thought about it.  Most of our platforms have MKL and the FFTW is picked up from there, but one of our platforms doesn't have MKL so we will have to do something else.  It isn't a problem, we will sort something out.

2024-06-28 09:21 UTC, wdeconinck commented
@DJDavies2 , FFTW (or MKL's implementation) is really improving performance quite a bit for most of the supported grids. Perhaps it is good that this was caught. 
As usual, also many thanks for testing the PRs on more architectures and configurations!

2024-06-28 09:22 UTC, wdeconinck approved these changes
Thanks @samhatfield !

2024-06-28 09:34 UTC, merged