Allow NOPT_MEMORY_TR to be controlled by driver command-line option.
ecmwf-ifs/ectrans pull request #136
Opened 2024-08-15 21:43 UTC by marsdeno

*Allows choosing between heap and stack for ZCOMBUF arrays in GTOL and LTOG transposition routines on the CPU. Silently ignored on the GPU.

2024-08-16 08:02 UTC, samhatfield commented
Looks good. But what's going on with the nvhpc builds?

2024-08-16 08:42 UTC, marsdeno commented
argh, the "No space left on device" is biting again
 
--
System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240815-214323-utc.log' at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset) at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite() at System.IO.StreamWriter.Flush(Boolean flushStream,

2024-08-16 08:56 UTC, samhatfield commented
Do we need to follow Balthasar's suggestion [here](https://github.com/ecmwf-ifs/ectrans/pull/127#issuecomment-2263325553)?

2024-08-16 08:58 UTC, marsdeno commented
Yes, am testing that at the moment in my fork

2024-08-19 09:57 UTC, samhatfield requested changes

2024-08-20 10:24 UTC, samhatfield approved these changes

2024-08-20 10:27 UTC, merged