Add current GPU codepath to main ectrans branch.
ecmwf-ifs/ectrans pull request #4
Opened 2022-06-22 14:15 UTC by marsdeno

Includes "reduced memory" codepath based on SUMMIT fixes by N Wedi

2022-06-22 14:15 UTC, FussyDuck commented
[![CLA assistant check](http://claassistant.ecmwf.int:80/pull/badge/not_signed)](http://claassistant.ecmwf.int:80/ecmwf-ifs/ectrans?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-ifs/ectrans?pullRequest=4) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: marsdeno<br/>:x: lukasm91<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-ifs/ectrans?pullRequest=4) it.</sub>

2022-06-23 08:12 UTC, wdeconinck requested changes

2022-06-23 08:12 UTC, wdeconinck commented on src/trans/gpu/CMakeLists.txt
> +set( HAVE_sp ${HAVE_SINGLE_PRECISION} )
Above 2 lines can be deleted. They are already present in outmost scope. I had moved them there because they are repeated in many places

2022-06-23 08:12 UTC, wdeconinck commented on src/trans/gpu/CMakeLists.txt
> +set( FFTW_sp FFTW::fftw3f )
Above 2 lines can be deleted. Variables are unused.

2022-06-23 11:16 UTC, samhatfield commented
Maybe we could also delete [this](https://github.com/marsdeno/ectrans/blob/gpu-rebase/src/trans/gpu/external/setup_trans.F90#L479)? It currently spits out a file for each MPI rank.

2022-07-01 10:43 UTC, samhatfield commented
Tested up to f5eb574 on Summit. Works great in non-CUDA-aware MPI form and with GPU_REDUCED_MEMORY disabled. With GPU_REDUCED_MEMORY disabled, we get:
```
free(): invalid next size (normal)
free(): invalid next size (normal)
free(): invalid size
double free or corruption (!prev)
free(): invalid next size (normal)
double free or corruption (!prev)
```
and no stack trace, though we believe this problem is specific to Summit.

2022-07-01 11:06 UTC, wdeconinck commented on src/trans/gpu/internal/parkind_ectrans.F90
> +#endif
Offline discussion points to having a trans_gpu_sp library possibility with a DP interface. 
Would be nice to add a CMake configuration option to enable this.
Currently such option would only affect the "gpu" library, but could later be extended to the "cpu" library as well.

2022-07-01 11:07 UTC, wdeconinck approved these changes

2022-07-04 10:17 UTC, samhatfield commented
The above error can be temporarily resolved by switching back from 3D arrays to flattened 1D arrays when calling GEMM in LEINV. See [this commit](https://github.com/samhatfield/ectrans/commit/1be9ad8506a171052aaf57de55d97db2a8a74bf6). I don't understand this yet.

2022-07-04 15:43 UTC, anmrde approved these changes
Looks good! Nice work!

2022-07-08 09:03 UTC, samhatfield commented
Whose signature is missing on the cla?

2022-07-08 09:32 UTC, wdeconinck commented
> Whose signature is missing on the cla?

This is Nvidia, see https://github.com/ecmwf-ifs/ectrans/pull/4#issuecomment-1163159756. This will either get sorted when legal teams agree, and @marsdeno is alternatively recreating a new PR without Nvidia's contributions.

2022-07-08 09:43 UTC, samhatfield commented
Oh right yeah - didn't realise Lukas had made contributions to this PR.

2022-07-10 19:17 UTC, samhatfield commented
Oh one other thing - could someone remove the print statements like `inv_trans: IF_FS_INV=...` and `dir_trans: IF_FS_DIR=...`? These are printed 8.6 million times in one of my 2.5 km RAPS runs, and that was only a 24-hour simulation.

2022-07-11 17:03 UTC, anmrde commented
I understand that the print statements `inv_trans: IF_FS_INV=...` and `dir_trans: IF_FS_DIR=...` can be annoying but I think this information is currently still quite important since we don't have a good way of knowing how to properly choose `IF_FS_DIR0`and `IF_FS_INV0` in setup_trans.F90. Right now our strategy is to hope for the best and if the print statements show that the values in setup_trans.F90 were too small we make them larger.

2022-07-11 20:16 UTC, samhatfield commented
Understood - we'll keep them for now (at least they are not put in the NODE.001_01 file).

2022-08-08 09:54 UTC, lukasm91 commented
FYI my version is not going to have those IF_FS_INV/... variables anymore.

2023-01-16 15:27 UTC, wdeconinck commented
What is the status of this PR ?

2023-01-16 16:16 UTC, marsdeno commented
Was waiting for something else to go in first, but as that is still not ready, I'll rebase this off latest and if you're good with it, we get it in. Following that can get Lukas' work in on top.

2023-01-16 16:44 UTC, anmrde commented
> 

It doesn't really matter since Lukas' version will make them completely obsolete. Lukas no longer allocates all the GPU arrays in setup_trans. That's much nicer than what we have right now!

2024-06-07 09:48 UTC, samhatfield commented
PR no longer relevant. redgreen-optimized is targeted for merging with develop.

2024-06-07 09:48 UTC, closed without merging